// src/components/BottomNav.vue
<script setup lang="ts">
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()

const tabs = [
  { name: 'inventory', label: '冰箱', icon: '🧊' },
  { name: 'discover', label: '推荐', icon: '✨' },
  { name: 'plan', label: '规划', icon: '📋' },
  { name: 'recipes', label: '菜谱', icon: '🍳' },
  { name: 'health', label: '健康', icon: '❤️' },
  { name: 'profile', label: '我', icon: '👤' },
] as const

function isActive(name: string) {
  return route.name === name
}

function navigate(name: string) {
  router.push({ name })
}
</script>

<template>
  <nav class="fixed bottom-0 left-1/2 z-50 w-full max-w-lg -translate-x-1/2 border-t border-slate-200 bg-white/95 backdrop-blur-md">
    <div class="flex items-center justify-around py-2">
      <button
        v-for="tab in tabs"
        :key="tab.name"
        :class="[
          'flex flex-col items-center gap-0.5 px-2 py-1 text-xs transition-colors',
          isActive(tab.name)
            ? 'text-amber-500'
            : 'text-slate-400 hover:text-slate-600'
        ]"
        @click="navigate(tab.name)"
      >
        <span class="text-lg">{{ tab.icon }}</span>
        <span>{{ tab.label }}</span>
      </button>
    </div>
  </nav>
</template>

// src/components/BottomNav.tsx
import { Refrigerator, Compass, Calendar, BookOpen, User } from 'lucide-react'

type Page = 'inventory' | 'discover' | 'plan' | 'recipes' | 'profile' | 'health'

const tabs: { id: Page; label: string; icon: typeof Refrigerator }[] = [
  { id: 'inventory', label: '冰箱', icon: Refrigerator },
  { id: 'discover', label: '推荐', icon: Compass },
  { id: 'plan', label: '规划', icon: Calendar },
  { id: 'profile', label: '我的', icon: User },
  { id: 'recipes', label: '菜谱', icon: BookOpen },
]

export default function BottomNav({
  current,
  onNavigate,
}: {
  current: Page
  onNavigate: (p: Page) => void
}) {
  return (
    <nav className="fixed inset-x-0 bottom-0 mx-auto max-w-lg border-t bg-white shadow-sm">

      <div className="flex">
        {tabs.map((tab) => {
          const isActive = current === tab.id
          const Icon = tab.icon
          return (
            <button
              key={tab.id}
              onClick={() => onNavigate(tab.id)}
              className={`flex flex-1 flex-col items-center gap-0.5 py-2 text-xs transition-all ${
                isActive
                  ? 'text-slate-800 font-medium'
                  : 'text-slate-400'
              }`}
            >
              <Icon size={20} />
              <span>{tab.label}</span>
            </button>
          )
        })}
      </div>
    </nav>
  )
}
